name: build

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      matrix:
        os: 
          - macos-latest    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install
          cmake
          openssl
          libplist
          gstreamer
          gst-plugins-base
          gst-plugins-good
          gst-plugins-bad
          gst-plugins-ugly
          gst-libav

      - name: Build Ludimus on macOS
        if: matrix.os == 'macos-latest'
        env:
          LIBRARY_PATH: "/usr/local/lib"
          CPATH: "/usr/local/include"
          LDFLAGS: "-L/usr/local/opt/openssl@1.1/lib"
          CPPFLAGS: "-I/usr/local/opt/openssl@1.1/include"
          PKG_CONFIG_PATH: "/usr/local/opt/openssl@1.1/lib/pkgconfig"
        run: |
          mkdir build
          cd build
          cmake ..
          make
