name: main

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - macos-latest
          - ubuntu-20.04
          - windows-latest
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install
          cmake
          openssl
          libplist
          gstreamer
          gst-plugins-base
          gst-plugins-good
          gst-plugins-bad
          gst-plugins-ugly
          gst-libav

      - name: Install Dependencies on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt install git
          cmake
          libssl-dev
          libplist-dev
          libavahi-compat-libdnssd-dev
          libgstreamer1.0-dev
          libgstreamer-plugins-base1.0-dev
          gstreamer1.0-plugins-base
          gstreamer1.0-plugins-good
          gstreamer1.0-plugins-bad
          gstreamer1.0-plugins-ugly
          gstreamer1.0-libav
          gstreamer1.0-vaapi
          gstreamer1.0-doc
          gstreamer1.0-tools
          gstreamer1.0-x
          gstreamer1.0-alsa
          gstreamer1.0-gl
          gstreamer1.0-gtk3
          gstreamer1.0-qt5
          gstreamer1.0-pulseaudio

      - name: Install Dependencies on Windows
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          install: git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-libplist
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-gst-plugins-base
            mingw-w64-x86_64-gst-plugins-good
            mingw-w64-x86_64-gst-plugins-bad
            mingw-w64-x86_64-gst-plugins-ugly
            mingw-w64-x86_64-gst-libav

      - name: Build Ludimus on macOS
        if: matrix.os == 'macos-latest'
        env:
          LIBRARY_PATH: "/usr/local/lib"
          CPATH: "/usr/local/include"
          LDFLAGS: "-L/usr/local/opt/openssl@1.1/lib"
          CPPFLAGS: "-I/usr/local/opt/openssl@1.1/include"
          PKG_CONFIG_PATH: "/usr/local/opt/openssl@1.1/lib/pkgconfig"
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Build Ludimus on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Build Ludimus on Windows
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          mingw32-make
